apiVersion: 1

datasources:
  - name: PostgreSQL
    uid: postgres-query-logs
    type: postgres
    access: proxy
    url: app_postgres:5432
    user: $POSTGRES_USER
    isDefault: true
    editable: true
    jsonData:
      database: $POSTGRES_DB
      sslmode: disable
      postgresVersion: 1600
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
    secureJsonData:
      password: $POSTGRES_PASSWORD
